### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by rostuhan** [FreedomScoops/FreedomScoops#6]
I feel like this project should have its own Discord server.

**Comment by ZNukem** [comment]
Much as I love to create a new Discord server or place for Freedom Scoops, I think it is best and easier to manage everything in one place on the Luke Ken Discord server, since it is also tied to that universe as a sub-verse. 

Adding a fourth server on my server list, on top of managing my DN fan community DNC, would be too much for me to operate at the moment. Mainly just doing this project as a hobby on my spare time. It’s really up to me if I decide to create one in the future, but for now, I just want to keep things simple as they are. I hope you understand. 😎

**Comment by rostuhan** [comment]
I didn't know about that server actually! Thank you for telling me about this.
